# ficheiro para comunicação assincrona - ideal para "Pedido Pronto"

version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672" # porta para comunicação com aplicações
      - "15672:15672" # port para acessar o painel de controle
    
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: always